# Generated by Django 3.2.3 on 2021-07-13 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0011_auto_20210626_1543'),
        ('users', '0004_auto_20210709_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electoralroll.legislativeassembly'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electoralroll.city'),
        ),
    ]
