# Generated by Django 3.1.5 on 2021-01-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislativeassembly',
            name='submitted_by',
        ),
    ]
