# Generated by Django 3.1.5 on 2021-01-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0002_remove_legislativeassembly_submitted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='legislativeassembly',
            options={'verbose_name_plural': 'legislative_assemblies'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name_plural': 'Voters'},
        ),
    ]
