# Generated by Django 3.1.5 on 2021-01-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0003_auto_20210126_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='husband_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
