# Generated by Django 3.1.5 on 2021-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0004_voter_husband_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
