# Generated by Django 3.1.5 on 2021-06-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0005_auto_20210214_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='Serial_no',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='UID',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
