# Generated by Django 3.1.5 on 2021-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0006_auto_20210621_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Serial_no',
            field=models.CharField(blank=True, default='-', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='UID',
            field=models.CharField(blank=True, default='-', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.CharField(blank=True, default='-', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='father_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='house_no',
            field=models.CharField(blank=True, default='-', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='husband_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
