# Generated by Django 3.1.5 on 2021-06-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0007_auto_20210622_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='assembly',
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number_name', models.CharField(max_length=10)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electoralroll.legislativeassembly')),
            ],
            options={
                'verbose_name_plural': 'part_numbers',
                'db_table': 'part_number',
            },
        ),
        migrations.AddField(
            model_name='voter',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electoralroll.partnumber'),
            preserve_default=False,
        ),
    ]
