# Generated by Django 3.2.3 on 2021-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0008_auto_20210624_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='anubhag',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
