# Generated by Django 3.1.5 on 2021-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0010_auto_20210624_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnumber',
            old_name='part_number_name',
            new_name='part_number',
        ),
        migrations.AddField(
            model_name='partnumber',
            name='part_location',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='part_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='voter_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
