# Generated by Django 3.2.3 on 2021-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0014_auto_20210731_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnumber',
            options={'ordering': ['part_number'], 'verbose_name_plural': 'part_numbers'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ['Serial_no'], 'verbose_name_plural': 'Voters'},
        ),
        migrations.AlterField(
            model_name='voter',
            name='Serial_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
