# Generated by Django 3.2.3 on 2021-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoralroll', '0015_auto_20210807_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='part_number',
            field=models.PositiveIntegerField(),
        ),
    ]
